# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CnQqZstZfGsZYpyq4TpjnoUkzSaNTTXY

Flood Fill function
"""

def flood_fill(input_board, old, new, x, y):
    """Recursively fills connected cells with a new value based on the old value."""
    # Base case: Check if the coordinates (x, y) are out of bounds or if the cell is not the old value.
    if x < 0 or x >= len(input_board) or y < 0 or y >= len(input_board[0]) or input_board[x][y] != old:
        return

    # Replace the old value with the new value at the current cell.
    input_board[x] = input_board[x][:y] + new + input_board[x][y + 1:]

    # Recursively fill adjacent cells.
    flood_fill(input_board, old, new, x + 1, y)
    flood_fill(input_board, old, new, x - 1, y)
    flood_fill(input_board, old, new, x, y + 1)
    flood_fill(input_board, old, new, x, y - 1)

